name: ferrytools
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0-16.0.dev

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/anan/anan_base.png
    - assets/anan/anan_happy.png
    - assets/anan/anan_speechless.png
    - assets/anan/anan_yandere.png
    - assets/anan/anan_blush.png
    - assets/anan/anan_angry.png
